version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "cron"
      cronjob: "0 9 16 * *"
    versioning-strategy: "increase"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "cron"
      cronjob: "0 9 16 * *"
    labels:
      - "dependencies"
      - "ci"
